# Generated by Django 5.0.1 on 2025-05-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('squad', models.CharField(max_length=100)),
                ('competition', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('year_born', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('matches_started', models.IntegerField()),
                ('minutes_played', models.IntegerField()),
                ('minutes_90s', models.FloatField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('goals_assists', models.IntegerField()),
                ('goals_no_penalty', models.IntegerField()),
                ('penalties_made', models.IntegerField()),
                ('penalties_attempted', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('expected_goals', models.FloatField()),
                ('expected_goals_no_penalty', models.FloatField()),
                ('expected_assists', models.FloatField()),
                ('expected_goals_plus_assists_no_penalty', models.FloatField()),
                ('progressive_carries', models.IntegerField()),
                ('progressive_passes', models.IntegerField()),
                ('progressive_dribbles', models.IntegerField()),
                ('goals_per90', models.FloatField()),
                ('assists_per90', models.FloatField()),
                ('goals_assists_per90', models.FloatField()),
                ('goals_no_penalty_per90', models.FloatField()),
                ('goals_assists_no_penalty_per90', models.FloatField()),
                ('expected_goals_per90', models.FloatField()),
                ('expected_assists_per90', models.FloatField()),
                ('expected_goals_assists_per90', models.FloatField()),
                ('expected_goals_no_penalty_per90', models.FloatField()),
                ('expected_goals_assists_no_penalty_per90', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['name'], name='players_pla_name_f5b1bf_idx'), models.Index(fields=['squad'], name='players_pla_squad_11c544_idx'), models.Index(fields=['position'], name='players_pla_positio_2502c1_idx'), models.Index(fields=['rank'], name='players_pla_rank_928dca_idx'), models.Index(fields=['competition'], name='players_pla_competi_41d841_idx')],
            },
        ),
    ]
