# Generated by Django 5.2.1 on 2025-05-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='players_pla_rank_928dca_idx',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='year_born',
        ),
    ]
