# Generated by Django 5.2.1 on 2025-05-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='expected_goals_plus_assists_no_penalty',
            new_name='expected_goals_assists',
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='players_name_0574eb_idx',
            old_name='players_pla_name_f5b1bf_idx',
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='players_squad_9ebeca_idx',
            old_name='players_pla_squad_11c544_idx',
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='players_positio_0bd0a3_idx',
            old_name='players_pla_positio_2502c1_idx',
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='players_competi_8cba2f_idx',
            old_name='players_pla_competi_41d841_idx',
        ),
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
    ]
