# Generated by Django 5.0.1 on 2025-11-16 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_expected_goals_plus_assists_no_penalty_player_expected_goals_assists_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='players.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_shortlist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_shortl_user_id_a3c766_idx'), models.Index(fields=['player'], name='user_shortl_player__e96482_idx')],
                'unique_together': {('user', 'player')},
            },
        ),
    ]
